spring:
  application:
    name: osc_user_center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/osc
    username: root
    password: 2469
  session:
    timeout: 86400
  data:
    redis:
      port: 6379
      host: 127.0.0.1
      database: 2
      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池的最大数据库连接数
          max-active: 8
          # #连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
minio: # MinIO连接信息
  # 访问资源的 URL
  url: "http://localhost:9000/"
  # 上传的 Bucket
  bucket: data
  # Access Key
  access-key: qpOxDTgSUDyWk1sUOiHO
  # Secret Key
  secret-key: A02ZMIWO9OKe57EcbMNcSC5kmO6gAu7sL9Yl55aJ

server:
  port: 8080
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑删除值
      logic-not-delete-value: 0 # 逻辑未删除值
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true # 开启增强
  setting:
    enable-swagger-models: true     # 开启SwaggerModels自定义名称
    swagger-model-name: 模块类     # SwaggerModels自定义名称
    enable-home-custom: true      # 自定义主页内容
    home-custom-path: classpath:markdown/home.md    # 主页的Markdown文件位置
    enable-footer: false    # 关闭原始Footer
    enable-footer-custom: true     # 开启自定义Footer
    footer-custom-content: 版权所有   # 自定义Footer内容
  production: false # 是否为生产环境（生产环境会屏蔽接口文档）